// Generated by HybirdPB CodeGenerator(1.1.2). DO NOT EDIT!
// Generation date is 2017-01-14 21:42:00


#import "APBConfig.h"

#ifndef SUPPORT_PB

@interface APBBisUploadGwResult:NSObject
@property (nonatomic,strong) NSString* retCode ;
@property (nonatomic,strong) NSString* retMessage ;
@property (nonatomic,strong) NSString* extInfo ;
@end


#else

#import <APProtocolBuffers/ProtocolBuffers.h>

@class APBBisUploadGwResult;

@interface APBBisUploadGwResult : APDPBGeneratedMessage

@property (readonly) BOOL hasRetCode;
@property (readonly) BOOL hasRetMessage;
@property (readonly) BOOL hasExtInfo;

@property (nonatomic,strong) NSString* retCode ;
@property (nonatomic,strong) NSString* retMessage ;
@property (nonatomic,strong) NSString* extInfo ;


@end
#endif
